CC = g++
CXXFLAGS = -Wall -Werror -fno-builtin-strcat -fno-builtin-strcpy -fno-builtin-strlen -g
OBJECTS = String.o StringTest.o

all: StringTest

StringTest: String.o StringTest.o

clean:
	rm -f *.o *~ StringTest
